aws:
  region: "ap-south-1"
  model_package_group_name: "mlops-model-group"
  pipeline_name: "MLOpsPipelineVersioned"
  sagemaker_role_arn: "arn:aws:iam::194169602214:role/SageMakerPipelineExecutionRole"
  default_bucket: "amazon-sagemaker-194169602214-ap-south-1-4z6615tqnogku9"
  endpoint_name: "mlops-model-group-dev-endpoint"

infrastructure:
  training_instance: "ml.m5.large"
  inference_instance: "ml.m5.large"
  framework_version: "1.0-1"

metadata:
  project: "mlops"
  env: "dev"
