import os
import json
import tarfile
import joblib
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

if __name__ == "__main__":
    print("Executing automated pipeline model evaluation gate...")
    
    # 1. Unpack the model artifact generated by the training job
    model_path = "/opt/ml/processing/model/model.tar.gz"
    with tarfile.open(model_path) as tar:
        tar.extractall(path=".")
        
    model = joblib.load("model.joblib")
    
    # 2. Load the validation dataset split
    data = load_breast_cancer()
    _, X_test, _, y_test = train_test_split(
        data.data, data.target, test_size=0.2, random_state=42
    )
    
    # 3. Calculate evaluation metrics
    accuracy = model.score(X_test, y_test)
    print(f"Evaluated Model Validation Accuracy: {accuracy:.4f}")
    
    # 4. Generate the standardized SageMaker property schema
    report_dict = {
        "classification_metrics": {
            "accuracy": {
                "value": accuracy,
                "standard_deviation": "NaN"
            }
        }
    }
    
    # Save the report to the canonical output folder expected by SageMaker
    output_dir = "/opt/ml/processing/evaluation"
    os.makedirs(output_dir, exist_ok=True)
    
    with open(os.path.join(output_dir, "evaluation.json"), "w") as f:
        f.write(json.dumps(report_dict))
        
    print("Evaluation metadata json schema report written successfully.")
